# See https://github.com/binder-examples/conda
name: RADIS-ENV
channels:
- conda-forge
- astropy
dependencies:
- python
- numpy
- psutil
- toolz
- scipy
- matplotlib
- dill
- pandas
- partd
- dask
- plotly
- h5py
- numba
- astroquery
- pip
- pip:
  - radis>=0.9.26
  - jupyter-offlinenotebook
